PARSER_BEGIN(IdList)

public class IdList{
    public static void main(String args[]) throws ParseException{
        IdList parser = new IdList(System.in);
        parser.Inicio();
    }
}

PARSER_END(IdList)

SKIP : {" " | "\t" | "\n" | "\r"}

TOKEN : {
            <Id : ["a"-"z", "A"-"Z"] (["a"-"z", "A"-"Z", "0"-"9"])*>
            {System.out.println("Encontré un identificador: " + image));}
        }

SKIP : {<~[]>}

void Inicio() : {}
{
    (<Id>)+<EOF>
}
