/* Generated By:JavaCC: Do not edit this line. SimpleExpressionConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleExpressionConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int If = 5;
  /** RegularExpression Id. */
  int Else = 6;
  /** RegularExpression Id. */
  int Then = 7;
  /** RegularExpression Id. */
  int leftBrace = 8;
  /** RegularExpression Id. */
  int rightBrace = 9;
  /** RegularExpression Id. */
  int Id = 10;
  /** RegularExpression Id. */
  int Constant = 11;
  /** RegularExpression Id. */
  int AddOperator = 12;
  /** RegularExpression Id. */
  int SubOperator = 13;
  /** RegularExpression Id. */
  int MulOperator = 14;
  /** RegularExpression Id. */
  int DivOperator = 15;
  /** RegularExpression Id. */
  int LeftParen = 16;
  /** RegularExpression Id. */
  int RightParen = 17;
  /** RegularExpression Id. */
  int LessThan = 18;
  /** RegularExpression Id. */
  int GreaterThan = 19;
  /** RegularExpression Id. */
  int LessEqualThan = 20;
  /** RegularExpression Id. */
  int GreaterEqualThan = 21;
  /** RegularExpression Id. */
  int EqualEqual = 22;
  /** RegularExpression Id. */
  int Different = 23;
  /** RegularExpression Id. */
  int Equal = 24;
  /** RegularExpression Id. */
  int Semicolon = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"if\"",
    "\"else\"",
    "\"then\"",
    "\"{\"",
    "\"}\"",
    "<Id>",
    "<Constant>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"=\"",
    "\";\"",
  };

}
