/* Generated By:JavaCC: Do not edit this line. SimpleExpressionConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleExpressionConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int id = 5;
  /** RegularExpression Id. */
  int constant = 6;
  /** RegularExpression Id. */
  int addOperator = 7;
  /** RegularExpression Id. */
  int subOperator = 8;
  /** RegularExpression Id. */
  int mulOperator = 9;
  /** RegularExpression Id. */
  int divOperator = 10;
  /** RegularExpression Id. */
  int leftParen = 11;
  /** RegularExpression Id. */
  int rightParen = 12;
  /** RegularExpression Id. */
  int equals = 13;
  /** RegularExpression Id. */
  int semicolon = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<id>",
    "<constant>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\";\"",
    "\"##\"",
  };

}
