/* Generated By:JavaCC: Do not edit this line. CMinusConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CMinusConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Else = 7;
  /** RegularExpression Id. */
  int If = 8;
  /** RegularExpression Id. */
  int Int = 9;
  /** RegularExpression Id. */
  int Return = 10;
  /** RegularExpression Id. */
  int Void = 11;
  /** RegularExpression Id. */
  int While = 12;
  /** RegularExpression Id. */
  int Real = 13;
  /** RegularExpression Id. */
  int Plus = 14;
  /** RegularExpression Id. */
  int Minus = 15;
  /** RegularExpression Id. */
  int Multiplier = 16;
  /** RegularExpression Id. */
  int Slash = 17;
  /** RegularExpression Id. */
  int LeftAngularBracket = 18;
  /** RegularExpression Id. */
  int RightAngularBracket = 19;
  /** RegularExpression Id. */
  int Equal = 20;
  /** RegularExpression Id. */
  int LeftAngularEqual = 21;
  /** RegularExpression Id. */
  int RightAngularEqual = 22;
  /** RegularExpression Id. */
  int EqualEqual = 23;
  /** RegularExpression Id. */
  int BangEqual = 24;
  /** RegularExpression Id. */
  int Semicolon = 25;
  /** RegularExpression Id. */
  int Comma = 26;
  /** RegularExpression Id. */
  int LeftParen = 27;
  /** RegularExpression Id. */
  int RightParen = 28;
  /** RegularExpression Id. */
  int LeftSquareBracket = 29;
  /** RegularExpression Id. */
  int RightSquareBracket = 30;
  /** RegularExpression Id. */
  int LeftBrace = 31;
  /** RegularExpression Id. */
  int RightBrace = 32;
  /** RegularExpression Id. */
  int Id = 33;
  /** RegularExpression Id. */
  int Number = 34;
  /** RegularExpression Id. */
  int Decimal = 35;
  /** RegularExpression Id. */
  int BadId = 40;
  /** RegularExpression Id. */
  int BadFloat1 = 41;
  /** RegularExpression Id. */
  int BadFloat2 = 42;
  /** RegularExpression Id. */
  int Error = 43;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int InsideText = 1;
  /** Lexical state. */
  int AnotherInsideText = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 3>",
    "\"//\"",
    "\"\\n\"",
    "<token of kind 6>",
    "\"else\"",
    "\"if\"",
    "\"int\"",
    "\"return\"",
    "\"void\"",
    "\"while\"",
    "\"real\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "<LeftAngularEqual>",
    "<RightAngularEqual>",
    "<EqualEqual>",
    "<BangEqual>",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "<Id>",
    "<Number>",
    "<Decimal>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<BadId>",
    "<BadFloat1>",
    "<BadFloat2>",
    "<Error>",
  };

}
