/* Generated By:JavaCC: Do not edit this line. CMinusConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CMinusConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Keywords = 4;
  /** RegularExpression Id. */
  int Plus = 5;
  /** RegularExpression Id. */
  int Minus = 6;
  /** RegularExpression Id. */
  int Multiplier = 7;
  /** RegularExpression Id. */
  int Slash = 8;
  /** RegularExpression Id. */
  int OpenLeftAngularBracket = 9;
  /** RegularExpression Id. */
  int OpenRightAngularBracket = 10;
  /** RegularExpression Id. */
  int Equal = 11;
  /** RegularExpression Id. */
  int LeftAngularEqual = 12;
  /** RegularExpression Id. */
  int RightAngularEqual = 13;
  /** RegularExpression Id. */
  int EqualEqual = 14;
  /** RegularExpression Id. */
  int Different = 15;
  /** RegularExpression Id. */
  int Semicolon = 16;
  /** RegularExpression Id. */
  int Comma = 17;
  /** RegularExpression Id. */
  int LeftParen = 18;
  /** RegularExpression Id. */
  int RightParen = 19;
  /** RegularExpression Id. */
  int LeftSquareBracket = 20;
  /** RegularExpression Id. */
  int RightSquareBracket = 21;
  /** RegularExpression Id. */
  int LeftBrace = 22;
  /** RegularExpression Id. */
  int RightBrace = 23;
  /** RegularExpression Id. */
  int Id = 24;
  /** RegularExpression Id. */
  int Number = 25;
  /** RegularExpression Id. */
  int Decimal = 26;
  /** RegularExpression Id. */
  int BadId = 31;
  /** RegularExpression Id. */
  int BadFloat1 = 32;
  /** RegularExpression Id. */
  int BadFloat2 = 33;
  /** RegularExpression Id. */
  int Error = 34;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int InsideText = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 3>",
    "<Keywords>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "<LeftAngularEqual>",
    "<RightAngularEqual>",
    "<EqualEqual>",
    "<Different>",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "<Id>",
    "<Number>",
    "<Decimal>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<BadId>",
    "<BadFloat1>",
    "<BadFloat2>",
    "<Error>",
  };

}
