/* Generated By:JavaCC: Do not edit this line. CMinusConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CMinusConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Else = 4;
  /** RegularExpression Id. */
  int If = 5;
  /** RegularExpression Id. */
  int Int = 6;
  /** RegularExpression Id. */
  int Return = 7;
  /** RegularExpression Id. */
  int Void = 8;
  /** RegularExpression Id. */
  int While = 9;
  /** RegularExpression Id. */
  int Real = 10;
  /** RegularExpression Id. */
  int Input = 11;
  /** RegularExpression Id. */
  int Output = 12;
  /** RegularExpression Id. */
  int Plus = 13;
  /** RegularExpression Id. */
  int Minus = 14;
  /** RegularExpression Id. */
  int Multiplier = 15;
  /** RegularExpression Id. */
  int Slash = 16;
  /** RegularExpression Id. */
  int OpenLeftAngularBracket = 17;
  /** RegularExpression Id. */
  int OpenRightAngularBracket = 18;
  /** RegularExpression Id. */
  int Equal = 19;
  /** RegularExpression Id. */
  int LeftAngularEqual = 20;
  /** RegularExpression Id. */
  int RightAngularEqual = 21;
  /** RegularExpression Id. */
  int EqualEqual = 22;
  /** RegularExpression Id. */
  int Different = 23;
  /** RegularExpression Id. */
  int Semicolon = 24;
  /** RegularExpression Id. */
  int Comma = 25;
  /** RegularExpression Id. */
  int LeftParen = 26;
  /** RegularExpression Id. */
  int RightParen = 27;
  /** RegularExpression Id. */
  int LeftSquareBracket = 28;
  /** RegularExpression Id. */
  int RightSquareBracket = 29;
  /** RegularExpression Id. */
  int LeftBrace = 30;
  /** RegularExpression Id. */
  int RightBrace = 31;
  /** RegularExpression Id. */
  int Id = 32;
  /** RegularExpression Id. */
  int Number = 33;
  /** RegularExpression Id. */
  int Decimal = 34;
  /** RegularExpression Id. */
  int BadId = 39;
  /** RegularExpression Id. */
  int BadFloat1 = 40;
  /** RegularExpression Id. */
  int BadFloat2 = 41;
  /** RegularExpression Id. */
  int Error = 42;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int InsideText = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 3>",
    "\"else\"",
    "\"if\"",
    "\"int\"",
    "\"return\"",
    "\"void\"",
    "\"while\"",
    "\"real\"",
    "\"input\"",
    "\"output\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "<LeftAngularEqual>",
    "<RightAngularEqual>",
    "<EqualEqual>",
    "<Different>",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "<Id>",
    "<Number>",
    "<Decimal>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<BadId>",
    "<BadFloat1>",
    "<BadFloat2>",
    "<Error>",
  };

}
