/* Generated By:JavaCC: Do not edit this line. CMinusConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CMinusConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Keywords = 1;
  /** RegularExpression Id. */
  int Plus = 2;
  /** RegularExpression Id. */
  int Minus = 3;
  /** RegularExpression Id. */
  int Multiplier = 4;
  /** RegularExpression Id. */
  int Slash = 5;
  /** RegularExpression Id. */
  int OpenLeftAngularBracket = 6;
  /** RegularExpression Id. */
  int OpenRightAngularBracket = 7;
  /** RegularExpression Id. */
  int Equal = 8;
  /** RegularExpression Id. */
  int LeftAngularEqual = 9;
  /** RegularExpression Id. */
  int RightAngularEqual = 10;
  /** RegularExpression Id. */
  int EqualEqual = 11;
  /** RegularExpression Id. */
  int Different = 12;
  /** RegularExpression Id. */
  int Semicolon = 13;
  /** RegularExpression Id. */
  int Comma = 14;
  /** RegularExpression Id. */
  int LeftParen = 15;
  /** RegularExpression Id. */
  int RightParen = 16;
  /** RegularExpression Id. */
  int LeftSquareBracket = 17;
  /** RegularExpression Id. */
  int RightSquareBracket = 18;
  /** RegularExpression Id. */
  int LeftBrace = 19;
  /** RegularExpression Id. */
  int RightBrace = 20;
  /** RegularExpression Id. */
  int Id = 21;
  /** RegularExpression Id. */
  int Number = 22;
  /** RegularExpression Id. */
  int Decimal = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<Keywords>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "<LeftAngularEqual>",
    "<RightAngularEqual>",
    "<EqualEqual>",
    "<Different>",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "<Id>",
    "<Number>",
    "<Decimal>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 28>",
    "<token of kind 29>",
    "<token of kind 30>",
    "<token of kind 31>",
  };

}
