/* Generated By:JavaCC: Do not edit this line. SimpleGrammarConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Comma = 1;
  /** RegularExpression Id. */
  int Boolean = 2;
  /** RegularExpression Id. */
  int Char = 3;
  /** RegularExpression Id. */
  int Id = 4;
  /** RegularExpression Id. */
  int BadId = 9;
  /** RegularExpression Id. */
  int Error = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\",\"",
    "\"boolean\"",
    "\"char\"",
    "<Id>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<BadId>",
    "<Error>",
  };

}
