# Generated by Django 3.0 on 2019-12-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complainer_response_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='responsible_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='responsible_response_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='strategic_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.StrategicProcess'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='subdivision_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SubdivisionReponsible'),
        ),
    ]
