# Generated by Django 3.0 on 2019-12-08 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191208_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='compliant_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ComplaintState'),
        ),
    ]
