/* Generated By:JavaCC: Do not edit this line. CompleteListAnalizerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompleteListAnalizerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SubjectCode = 5;
  /** RegularExpression Id. */
  int Subject = 6;
  /** RegularExpression Id. */
  int Day = 7;
  /** RegularExpression Id. */
  int Days = 8;
  /** RegularExpression Id. */
  int Hour = 9;
  /** RegularExpression Id. */
  int Hours = 10;
  /** RegularExpression Id. */
  int Room = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SubjectCode>",
    "<Subject>",
    "<Day>",
    "<Days>",
    "<Hour>",
    "<Hours>",
    "<Room>",
    "<token of kind 12>",
  };

}
