/* Generated By:JavaCC: Do not edit this line. BinaryConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BinaryConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Zero = 4;
  /** RegularExpression Id. */
  int One = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"0\"",
    "\"1\"",
    "\"\\n\"",
  };

}
