# Generated by Django 2.2.7 on 2019-11-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paradigm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('firstAppeared', models.IntegerField()),
                ('lastVersion', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=50)),
                ('paradigms', models.ManyToManyField(to='api.Paradigm')),
            ],
        ),
    ]
